apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: swiggy-container
          image: kastrov/swiggy
          ports:
            - containerPort: 3000  # Your app runs on port 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  selector:
    app: swiggy
  ports:
    - protocol: TCP
      port: 80          # External port exposed to the world
      targetPort: 3000  # App container listens on 3000
  type: LoadBalancer
